name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Compilar código fuente
        run: |
          cd proyecto
          mkdir -p out
          javac -d out src/main/java/PayrollService.java src/test/java/PayrollServiceTest.java

      - name: Ejecutar pruebas
        run: |
          cd proyecto
          java -cp out PayrollServiceTest